main: su.nightexpress.dungeons.DungeonPlugin
version: '${project.version}'
name: AdvancedDungeonArena
description: Advanced and poweful dungeon & mob arena creator.
author: NightExpress
depend: [ nightcore ]
softdepend:
  - MythicMobs
  - mcMMO
  - PlaceholderAPI
  - CombatPets

api-version: 1.21