main: su.nightexpress.dungeons.DungeonPlugin
version: ${version}
name: AdvancedDungeonArena
description: Advanced and powerful dungeon & mob arena creator.
author: NightExpress
depend: [ nightcore ]
softdepend:
  - MythicMobs
  - mcMMO
  - PlaceholderAPI
  - CombatPets

api-version: 1.21